//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JF.DAL.Context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class jobzFactoryEntities : DbContext
    {
        public jobzFactoryEntities()
            : base("name=jobzFactoryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<ActionOffre> ActionOffre { get; set; }
        public virtual DbSet<Codification> Codification { get; set; }
        public virtual DbSet<Offre> Offre { get; set; }
        public virtual DbSet<Offre_Historique> Offre_Historique { get; set; }
        public virtual DbSet<Offre_Postuler> Offre_Postuler { get; set; }
        public virtual DbSet<Pays> Pays { get; set; }
        public virtual DbSet<Profil> Profil { get; set; }
        public virtual DbSet<Profil_CV> Profil_CV { get; set; }
        public virtual DbSet<Profil_Link> Profil_Link { get; set; }
        public virtual DbSet<Recruteur> Recruteur { get; set; }
        public virtual DbSet<Recruteur_Contact> Recruteur_Contact { get; set; }
        public virtual DbSet<SecteurActivite> SecteurActivite { get; set; }
        public virtual DbSet<Ville> Ville { get; set; }
    }
}
