//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JF.DAL.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Offre_Historique
    {
        public int id { get; set; }
        public int C_idOffre { get; set; }
        public System.DateTime dateAction { get; set; }
        public int C_idTypeAction { get; set; }
        public int C_idUtilisateur { get; set; }
        public string commentaire { get; set; }
    
        public virtual ActionOffre ActionOffre { get; set; }
        public virtual Offre Offre { get; set; }
    }
}
