//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JF.DAL.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Offre
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Offre()
        {
            this.Offre_Historique = new HashSet<Offre_Historique>();
            this.Offre_Postuler = new HashSet<Offre_Postuler>();
        }
    
        public int id { get; set; }
        public string message { get; set; }
        public int C_idRecruteur { get; set; }
        public Nullable<int> C_idVille { get; set; }
        public bool isPublie { get; set; }
        public string titreOffre { get; set; }
        public Nullable<int> C_idSecteurActivite { get; set; }
        public string url { get; set; }
        public Nullable<bool> isConfidentiel { get; set; }
        public string adresseMailAPostuler { get; set; }
        public string nomImage { get; set; }
        public Nullable<int> numberOffre { get; set; }
    
        public virtual Codification Codification { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Offre_Historique> Offre_Historique { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Offre_Postuler> Offre_Postuler { get; set; }
        public virtual Recruteur Recruteur { get; set; }
        public virtual SecteurActivite SecteurActivite { get; set; }
        public virtual Ville Ville { get; set; }
    }
}
