//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JF.DAL.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profil
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Profil()
        {
            this.Offre_Postuler = new HashSet<Offre_Postuler>();
            this.Profil_CV = new HashSet<Profil_CV>();
            this.Profil_Link = new HashSet<Profil_Link>();
        }
    
        public int id { get; set; }
        public string nom { get; set; }
        public string prenom { get; set; }
        public Nullable<System.DateTime> dateNaissance { get; set; }
        public string adresseMail { get; set; }
        public string gsm { get; set; }
        public string Tel { get; set; }
        public string motPasse { get; set; }
        public System.DateTime dateCreation { get; set; }
        public string titre { get; set; }
        public Nullable<int> C_idVille { get; set; }
        public string adresse { get; set; }
        public Nullable<int> C_idSecteur { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Offre_Postuler> Offre_Postuler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Profil_CV> Profil_CV { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Profil_Link> Profil_Link { get; set; }
        public virtual SecteurActivite SecteurActivite { get; set; }
        public virtual Ville Ville { get; set; }
    }
}
