//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JF.DAL.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profil_Link
    {
        public int id { get; set; }
        public int C_idProfil { get; set; }
        public System.DateTime dateGeneration { get; set; }
        public string token { get; set; }
        public System.DateTime dateExpiration { get; set; }
        public Nullable<System.DateTime> dateActivation { get; set; }
        public bool etat { get; set; }
    
        public virtual Profil Profil { get; set; }
    }
}
