//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JF.DAL.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profil_CV
    {
        public int id { get; set; }
        public int C_idProfil { get; set; }
        public System.DateTime DateCreation { get; set; }
        public string nomCV { get; set; }
        public string extantion { get; set; }
    
        public virtual Profil Profil { get; set; }
    }
}
