//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JF.DAL.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recruteur
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Recruteur()
        {
            this.Offre = new HashSet<Offre>();
            this.Recruteur_Contact = new HashSet<Recruteur_Contact>();
        }
    
        public int id { get; set; }
        public string nomRecruteur { get; set; }
        public string siteweb { get; set; }
        public string adresseMail { get; set; }
        public System.DateTime dateCreation { get; set; }
        public string url { get; set; }
        public string description { get; set; }
        public string adresseSocial { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Offre> Offre { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recruteur_Contact> Recruteur_Contact { get; set; }
    }
}
