//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JF.DAL.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recruteur_Contact
    {
        public int id { get; set; }
        public string nom { get; set; }
        public string prenom { get; set; }
        public string adresseMail { get; set; }
        public string compte { get; set; }
        public string motPasse { get; set; }
        public System.DateTime dateCreation { get; set; }
        public Nullable<int> profil { get; set; }
        public Nullable<int> C_idRecruteur { get; set; }
    
        public virtual Recruteur Recruteur { get; set; }
    }
}
